todo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView

from views import ViewTodoList,Show_Items,Add_List,Add_List_Items,Update_List_Items,Delete_List_item,Update_List,Delete_List

from . import views

urlpatterns = [
    url(r'^todolist/$',(ViewTodoList.as_view()),name='todolistall'),
    url(r'^todolist/(?P<item>[0-9]+)/$',Show_Items.as_view(),name='showitems'),
    url(r'^todolist/addlist/$',Add_List.as_view(),name='addlist'),
    url(r'^todolist/updatelist/(?P<id>[0-9]+)/$',Update_List.as_view(),name='updatelist'),
    url(r'^todolist/deletelist/(?P<id>[0-9]+)/$',Delete_List.as_view(),name='deletelist'),
    url(r'^todolist/(?P<item>[0-9]+)/add/$',Add_List_Items.as_view(),name='addlistitems'),
    url(r'^todolist/(?P<item>[0-9]+)/update/(?P<id>[0-9]+)/$', Update_List_Items.as_view(), name='updatelistitems'),
    url(r'^todolist/(?P<item>[0-9]+)/delete/(?P<id>[0-9]+)/$',Delete_List_item.as_view(), name='deletelistitems'),
]

todoproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.backends import django
from django.views.generic import  TemplateView
from todo.views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/',include('todo.urls')),
    url(r'^accounts/',include('django.contrib.auth.urls'),name='authentication'),
    url(r'^todolist/$',todolist),
    url(r'^todolist/(?P<id>[0-9]+)/$',todolistdetails),
    url(r'^todolistitems/(?P<id>[0-9]+)/$',todolistitems),
    url(r'^listitem/(?P<id>[0-9]+)/$',todolistitemsdetail),
    url(r'^backbone/$',TemplateView.as_view(template_name="todo/newtodo.html")),
    url(r'^angular/$',TemplateView.as_view(template_name="angularjsfile.html"))
]

todo/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Todolist(models.Model):
    owner=models.ForeignKey(User)
    name=models.CharField(max_length=100)
    created=models.DateField()
    def __str__(self):
        return self.name

class Todolistitem(models.Model):
    description=models.CharField(max_length=150)
    duedate=models.DateField()
    completed=models.BooleanField(default=False)
    parent=models.ForeignKey(Todolist)
    def __str__(self):
        return self.description

todo/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.template.loader import get_template

from .models import *

def todolist(request,owner):
    l=Todolistitem.objects.filter(parent__name__iexact=owner)
    template=get_template('todo/todolist.html')
    return HttpResponse(template.render(context={'listitems':l,'listname':owner}))

def todolistall(request):
    t = Todolist.objects.all()
    #print t
    #items = []
    #for i in t:
    #    l = Todolistitem.objects.values_list('description', 'duedate').filter(parent__name__iexact=i[0])
    #    s = [i, l]
    #    items.append(s)
    template=get_template('todo/todolistall.html')
    return HttpResponse(template.render(context={'items':t}))

todo/views/SerializerView.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from todo.models import *
from todo.serializers import *

@login_required
@api_view(['GET','POST'])
def todolist(request):
    if request.method=='GET':
        todos=Todolist.objects.filter(owner=request.user)
        serializer=TodoSerializer(todos,many=True)
        return Response(serializer.data)
    elif request.method=='POST':
        data=request.data
        data['owner']=request.user.id
        print(data)
        serializer=TodoSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@login_required
@api_view(['GET','PUT','DELETE'])
def todolistdetails(request,id):
    try:
        todos=Todolist.objects.get(pk=id)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method=='GET':
        t=TodoSerializer(todos)
        return Response(t.data)
    elif request.method=='PUT':
        data=request.data
        data['owner']=request.user.id
        s=TodoSerializer(todos,data=data)
        if s.is_valid():
            s.save()
            return Response(s.data)
        return Response(s.errors,status=status.HTTP_400_BAD_REQUEST)
    elif request.method=='DELETE':
        todos.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@login_required
@api_view(['GET','POST'])
def todolistitems(request,id):
    if request.method=='GET':
        todoitems=Todolistitem.objects.filter(parent_id=id)
        ser=TodoItemSerializer(todoitems,many=True)
        return Response(ser.data)
    elif request.method=='POST':
        data=request.data
        data['parent']=id
        ser=TodoItemSerializer(data=data)
        if ser.is_valid():
            ser.save()
            todoitems = Todolistitem.objects.filter(parent_id=id)
            ser = TodoItemSerializer(todoitems, many=True)
            return Response(ser.data)
        return Response(status=status.HTTP_404_NOT_FOUND)

@login_required
@api_view(['DELETE'])
def todolistitemsdetail(request,id):
    try:
        todoitem=Todolistitem.objects.get(id=id)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method=='DELETE':
        todoitem.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

todo/views/todolist_view.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.forms import forms
from django.forms.models import inlineformset_factory
from django.utils.decorators import method_decorator

from todo.models import Todolist,Todolistitem
from django.views.generic import ListView,CreateView,UpdateView,DeleteView


@method_decorator(login_required(),name='dispatch')
class ViewTodoList(ListView):
    model=Todolist
    template_name='todo/todolistall.html'
    context_object_name='items'

    def get_queryset(self):
        return Todolist.objects.filter(owner=self.request.user)


@method_decorator(login_required,name='dispatch')
class Add_List(CreateView):
    model=Todolist
    fields = ('name','created')
    template_name = 'todo/add_list.html'

    def form_valid(self, form):
        form.instance.owner=self.request.user
        return super(Add_List,self).form_valid(form)

    def get_success_url(self):
        return reverse('todolistall')

@method_decorator(login_required,name='dispatch')
class Update_List(UpdateView):
    model=Todolist
    fields = ('name','created')
    template_name = 'todo/add_list.html'

    def get_object(self, queryset=None):
        return Todolist.objects.get(id=self.kwargs.get('id'))

    def get_success_url(self):
        return reverse('todolistall')



@method_decorator(login_required,name='dispatch')
class Delete_List(DeleteView):
    model=Todolist
    template_name = 'todo/delete_item.html'

    def get_object(self, queryset=None):
        return Todolist.objects.get(id=self.kwargs.get('id'))

    def get_success_url(self):
        return reverse('todolistall')

todo/views/todolistitems.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator

from todo.models import Todolist,Todolistitem
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView

@method_decorator(login_required,name='dispatch')
class Show_Items(DetailView):
    model=Todolist
    template_name = 'todo/todolis.html'
    context_object_name = 'listitems'
    def get_context_data(self, **kwargs):
        context= super(Show_Items, self).get_context_data(**kwargs)
        context['items']=self.kwargs.get('item')
        return context

    def get_object(self, queryset=None):
        item=self.kwargs.get('item')
        if item:
            return Todolist.objects.get(id__iexact=item)
        else:
            return Todolist.objects.all()

@method_decorator(login_required,name='dispatch')
class Add_List_Items(CreateView):
    template_name = 'todo/add_list.html'
    model=Todolistitem
    fields = ('description','duedate','completed')

    def form_valid(self, form):
        form.instance.parent=Todolist.objects.get(id=self.kwargs.get('item'))
        return super(Add_List_Items,self).form_valid(form)

    def get_object(self, queryset=None):
        return Todolist.objects.get(id__iexact=self.kwargs.get('item'))

    def get_success_url(self):
        return reverse('showitems',kwargs={'item':self.kwargs.get('item')})

@method_decorator(login_required,name='dispatch')
class Update_List_Items(UpdateView):
    template_name = 'todo/add_list.html'
    model = Todolistitem
    fields = ('description','duedate','completed')

    def form_valid(self, form):
        form.instance.parent = Todolist.objects.get(id=self.kwargs.get('item'))
        return super(Update_List_Items, self).form_valid(form)

    def get_object(self, queryset=None):
        return Todolistitem.objects.get(id__iexact=self.kwargs.get('id'))

    def get_success_url(self):
        return reverse('showitems', kwargs={'item': self.kwargs.get('item')})

@method_decorator(login_required,name="dispatch")
class Delete_List_item(DeleteView):
    template_name = 'todo/delete_item.html'
    model=Todolistitem

    def get_object(self, queryset=None):
        return Todolistitem.objects.get(id__iexact=self.kwargs.get('id'))
    def get_success_url(self):
        return reverse('showitems', kwargs={'item': self.kwargs.get('item')})

todo/templates/todo/add_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%  load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <style>
  body {
      position: relative;
  }
  #section1 {padding-top:50px;color: #F25432; background-color: #9595ff;}
  #section2 {padding-top:50px;height:500px;color: #F25432; background-color: #F25432;}
  #section3 {padding-top:50px;height:500px;color: #FFF; background-color: #76F654;}
  #section4 {padding-top:50px;color: #6e87ff; background-color: #f8f4ff;}
  img{padding-left: 70%;height: 100px;}
  #section42 {padding-top:50px;height:500px;color: #fff; background-color: #009688;}
  </style>
</head>
<body>
<div id="section1" class="container">
    <form method="post" role="form">{% csrf_token %}
        <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}">Name  :</label>
            {{ form.name }}
            </div>
        <div class="form-group">
            {{ form.created.errors }}
            {{ form.created.label_tag }}
            {{ form.created }}
            </div>
        <div class="form-group">
        <input type="submit" value="ADD"/>
            </div>
    </form>
    </div>
</body>
</html>

todo/templates/todo/delete_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Item</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <h1>Are you Sure </h1>
        {{ form.as_p }}
        <input type="submit" value="Yes"/>
    </form>
</body>
</html>

todo/templates/todo/newtodo.html
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone-localstorage.js/1.1.16/backbone.localStorage-min.js" type="text/javascript"></script>  
</head>
<body>
    <div id="itemlist">
    <h2 >Todos</h2>
        <input type="text" placeholder="enter new todo item" id="inputitem"/>
    <script id="listscript" type="text/template">
        <li> <h3 id="item"><%= name %></h3>
        <input type="button" id="edititem" value="edit"/>
        <input type="button" id="deleteitem" value="delete"/></li>
    </script>
    <ol id="listview">
        </ol>
        </div>
    <script >

var TodoList=Backbone.Model.extend({
    default:{
        name:'',
        created:''
    }
});

var TodoListItems=Backbone.Collection.extend({
    model:TodoList,
     url:'http://127.0.0.1:8000/todolist/',

});

//var todo=new TodoList({name:'cprogramming',id:1,created:'25-05-2016'});
var todos=new TodoListItems();



var TodoItemView = Backbone.View.extend({
    template:_.template($('#listscript').html()),
    initialize:function(){
      this.render();
    },
    events:{
      'click #item':'showclick',
        'click #deleteitem':'deletemodel',
        'click #edititem':'editmodel',
    },
    showclick:function(){
      console.log(this.model.get('name'));
    },
    deletemodel:function(){
      this.model.destroy();
        this.remove();
    },
    editmodel:function(){
      var name=prompt("enter new title");
        this.model.save({name:name});
        console.log(name);
        this.render();
    },
    render:function(){
      this.$el.html(this.template(this.model.toJSON()));
        return this;
    },
});

var TodoListView=Backbone.View.extend({
    el:'#listview',
    initialize:function(){
        var self=this;
         this.collection.fetch({
            success: function(collection, response, options) {
                self.render();
            },
            error: function(model, responce, options) {
                console.log(options.xhr);
            }
        });
    },
    render:function(){
    this.collection.each(function(todoitem){
       var v=new TodoItemView({model:todoitem});
        this.$el.append(v.el);
    },this);
        return this;
}
});


var AppView=Backbone.View.extend({
    el:$('#itemlist'),
   initialize:function(){
     this.render();
   },events:{
     'keypress #inputitem':'keyPressFunction'
   },
    keyPressFunction:function(e){
      if(e.keyCode==13)
          {
              var string=$('#inputitem').val();
              console.log(string);
              $('#inputitem').val('')
              var t=new TodoList({name:string,date:'25-06-2016'});
              todos.create(t);
              var xhr=createCORSRequest("GET","http://127.0.0.1:8000/todolist/");
              console.log(xhr);
              if(xhr)
                  {
                      xhr.send();
                  }
              this.addOne(t);
          }
    },
    render:function(){
        todos.fetch();
        var v=new TodoListView({collection:todos});
        console.log(todos);
    },
     addOne:function(todo){
      var v=new TodoItemView({model:todo});
        this.$('#listview').append(v.el);
    },
});

$('document').ready(function(){
    console.log("File successfully compiled");
    //var v=new TodoItemView({model:todo,el:$('#item1')});
    //var v2=new TodoItemView({model:todo1,el:$('#item1')})
    //var v=new TodoListView({collection:todos});
    var a=new AppView();
});



function createCORSRequest(method, url){
    var xhr = new XMLHttpRequest();
    if ("withCredentials" in xhr){
        xhr.open(method, url, true);
    } else if (typeof XDomainRequest != "undefined"){
        xhr = new XDomainRequest();
        xhr.open(method, url);
    } else {
        xhr = null;
    }
    return xhr;
}
/*
var request = createCORSRequest("get", "http://www.nczonline.net/");
if (request){
    request.onload = function(){
        //do something with request.responseText
    };
    request.send();
}*/
    </script>
    </body>
</html>

todo/templates/todo/todobackbone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

todo/templates/todo/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo list</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%  load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <style>
  body {
      position: relative;
  }
  #section1 {padding-top:50px;color: #F25432; background-color: #9595ff;}
  #section2 {padding-top:50px;height:500px;color: #F25432; background-color: #F25432;}
  #section3 {padding-top:50px;height:500px;color: #FFF; background-color: #76F654;}
  #section4 {padding-top:50px;color: #6e87ff; background-color: #f8f4ff;}
  img{padding-left: 70%;height: 100px;}
  #section42 {padding-top:50px;height:500px;color: #fff; background-color: #009688;}
  </style>
</head>
<body>
    <div id="section1">
    <h2>List of Items in {{ listitems.name }}</h2>
        <div align="right"> <a href="/admin/logout"><button type="button" class="btn btn-primary">Logout</button></a></div>
    </div>
    <div id="section4" class="table-responsive">
    <table class="table table-hover">
    <tr>
        <th>Description</th>
        <th>DueDate</th>
        <th>completed</th>
        <th></th>
        <th></th>
    </tr>
    {% for i in listitems.todolistitem_set.all %}
        <tr>
            <td>{{ i.description }}</td>
            <td>{{ i.duedate }}</td>
            <td>{{ i.completed }}</td>
            <td><a href="/todo/todolist/{{ listitems.id }}/delete/{{ i.id }}"><span class="glyphicon glyphicon-remove"></span></a></td>
            <td><a href="/todo/todolist/{{ listitems.id }}/update/{{ i.id }}"><span class="glyphicon glyphicon-refresh"></span></a></td>
        </tr>
    {% endfor %}
    </table>
    <a href="/todo/todolist/{{ listitems.id }}/add"><button type="button" class="btn btn-primary">Add New Item</button></a>
    </div>
</body>
</html>

todo/templates/todo/todolistall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo List all</title>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    {%  load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <style>
  body {
      position: relative;
  }
  #section1 {padding-top:50px;color: #F25432; background-color: #9595ff;}
  #section2 {padding-top:50px;height:500px;color: #F25432; background-color: #F25432;}
  #section3 {padding-top:50px;height:500px;color: #FFF; background-color: #76F654;}
  #section4 {padding-top:50px;color: #6e87ff; background-color: #f8f4ff;}
  img{padding-left: 70%;height: 100px;}
  #section42 {padding-top:50px;height:500px;color: #fff; background-color: #009688;}
  </style>
</head>
<body>
    <div id="section1" class="container-fliud">
    <h1>All Lists</h1>
      <div align="right"> <a href="/admin/logout"><button type="button" class="btn btn-primary">Logout</button></a></div>
    </div>
    <div id="section4">
    <table class="table table-hover">
        <tr>
        <th>Lists</th>
        <th></th>
        <th></th>
        </tr>
        {% for o in items %}
            <tr>
            <td><a href="/todo/todolist/{{ o.id }}">{{ o.name }}</a></td>
            <td><a href="/todo/todolist/updatelist/{{ o.id }}"><span class="glyphicon glyphicon-refresh"></span></a></td>
            <td><a href="/todo/todolist/deletelist/{{ o.id }}"><span class="glyphicon glyphicon-remove"></span></a></td>
            </tr>
        {% endfor %}
    </table>
    <a href="/todo/todolist/addlist"><button type="button" class="btn btn-primary">Add New Item</button></a>
    </div>
</body>
</html>